ELIMS_MVC/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ELIMS_MVC.Authorization;
using ELIMS_MVC.Data;
using ELIMS_MVC.Models;
using ELIMS_MVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ELIMS_MVC.Controllers
{
    public class DashboardController : Controller
    {

        private readonly ELIMS_MVCContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IAuthorizationService _authorizationService;

        public ApplicationUser AppUser { get; set; }

        public DashboardController(ELIMS_MVCContext context, UserManager<ApplicationUser> userManager, IAuthorizationService authorizationService)
        {
            _context = context;
            _userManager = userManager;
            _authorizationService = authorizationService;
        }

        // GET: Users
        [Authorize]
        public async Task<IActionResult> Index()
        {
            ViewData["UserName"] = User.Identity.Name;

            var users = from u in _context.Users select u;

            var isAuthorized = User.IsInRole("ADMINISTRATORS");

            if (!isAuthorized)
            {
                return View("./AccessDenied");
            }

            return View(await users.ToListAsync());
        }

        // GET: Delete
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var isAuthorized = User.IsInRole("ADMINISTRATORS") || User.IsInRole("MANAGERS");

            if(!isAuthorized)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {

            var user = await _userManager.FindByIdAsync(id);

            if(user != null)
            {
                await _userManager.DeleteAsync(user);
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Edit
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,UserName,FirstName,LastName,Email,PhoneNumber,Status, LabAccess")] ApplicationUser user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (user == null)
                {
                    return NotFound();
                }

                var edited_user = await _userManager.FindByIdAsync(id);
                edited_user.Id = user.Id;
                edited_user.FirstName = user.FirstName;
                edited_user.LastName = user.LastName;
                edited_user.UserName = user.UserName;
                edited_user.Email = user.Email;
                edited_user.PhoneNumber = user.PhoneNumber;
                edited_user.Status = user.Status;
                edited_user.LabAccess = user.LabAccess;

                if (edited_user.Status == "Lab administrator")
                {
                    await _userManager.AddToRoleAsync(edited_user, "ADMINISTRATORS");

                }
                else if (edited_user.Status == "Student manager" || edited_user.Status =="Lab manager (non-student)")
                {
                    await _userManager.AddToRoleAsync(edited_user, "MANAGERS");

                }
                else if (edited_user.Status == "Student" || edited_user.Status == "Researcher (non-student)")
                {
                    await _userManager.AddToRoleAsync(edited_user, "USERS");

                }

                var result = await _userManager.UpdateAsync(edited_user);
                if (result.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                } else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }

                }

                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Details
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var isAuthorized = User.IsInRole("ADMINISTRATORS") || User.IsInRole("MANAGERS");

            if (!isAuthorized)
            {
                return NotFound();
            }

            return View(user);
        }


        private bool UserExists(string id)
        {
            return _context.Users.Any(e => e.Id == id);
        }

    }

}

ELIMS_MVC/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ELIMS_MVC.Models;
using Microsoft.AspNetCore.Authorization;
using MimeKit;
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Identity;
using ELIMS_MVC.Authorization;
using ELIMS_MVC.Data;

namespace ELIMS_MVC.Controllers
{
    public class RequestController : Controller
    {
        private readonly ELIMS_MVCContext _context;
        private readonly IAuthorizationService _authorizationService;
        private readonly UserManager<ApplicationUser> _userManager;


        public RequestController(ELIMS_MVCContext context, IAuthorizationService authorizationService, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _authorizationService = authorizationService;
            _userManager = userManager;
        }

        // GET: Requests
        [Authorize]
        public async Task<IActionResult> Index(string search, string requestStatus)
        {
            // Use LINQ to get list of topics
            var list = new List<string>() { "Approved", "Denied", "Pending"};
            var requestQuery = list.AsQueryable();

            var requests = from r in _context.Request select r;

            var isAuthorized = User.IsInRole("MANAGERS") || User.IsInRole("ADMINISTRATORS");

            var currentUserId = _userManager.GetUserId(User);

            // Requests are only shown if user is the owner or an admin/manager
            if (!isAuthorized)
            {
                requests = requests.Where(r => r.OwnerID == currentUserId);
            }

            if (!String.IsNullOrEmpty(search))
            {
                requests = requests.Where(s => s.LastName.Contains(search));
            }

            return View(await requests.ToListAsync());
        }

        // GET: Requests/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await _context.Request
                .FirstOrDefaultAsync(m => m.Id == id);
            if (request == null)
            {
                return NotFound();
            }

            var isAuthorized = User.IsInRole("MANAGERS") || User.IsInRole("ADMINISTRATORS");

            var currentUserId = _userManager.GetUserId(User);

            if (!isAuthorized
                && currentUserId != request.OwnerID
                && request.Status != RequestStatus.Approved)
            {
                return new ChallengeResult();
            }

            return View(request);
        }

        // POST: Requests/Details
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Details(int id, [Bind("Id,UserId,StartDate,EndDate,RequestMade,FirstName,LastName,NAUEmail,ProjectName,ProjectObjective,ContactName,ContactID,Funding,SponsorName,SponsorPhone,SponsorEmail,Chemicals,MeetingTimes,GroupMembers,ProjectFile,Status,OwnerID")] Request request)
        {
            var status = request.Status;

            var r = await _context.Request.FindAsync(id);


            if (r == null)
            {
                return NotFound();
            }

            if (id != request.Id)
            {
                return NotFound();
            }

            var requestOperation = (status == RequestStatus.Approved) ? ELIMSOperations.Approve : ELIMSOperations.Deny;

            var isAuthorized = await _authorizationService.AuthorizeAsync(User, r, requestOperation);

            if (!isAuthorized.Succeeded)
            {
                return new ChallengeResult();
            }

            r.Status = status;
            _context.Request.Update(r);
            await _context.SaveChangesAsync();

            //var autoEmail = new MimeMessage();
            //autoEmail.From.Add(new MailboxAddress("donotreplyelims@gmail.com"));

            //// Email the user who made the request that their request has been updated
            //autoEmail.To.Add(new MailboxAddress(request.NAUEmail));
            //autoEmail.Subject = "ELIMS Lab Request Notification";
            //autoEmail.Body = new TextPart("plain")
            //{
            //    Text = @"There has been an update to your lab usage request. Please click this link to view it: https://elims.azurewebsites.net/request. Do not reply to this email. Thank you!"
            //};

            //using (var client = new SmtpClient())
            //{
            //    client.ServerCertificateValidationCallback = (s, c, h, e) => true;


            //    client.Connect("smtp.gmail.com", 587, false);
            //    client.Authenticate("donotreplyelims@gmail.com", "NAULabs123");
            //    client.Send(autoEmail);
            //    client.Disconnect(true);
            //}

            return RedirectToAction(nameof(Index));

        }

        // GET: Requests/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Requests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,StartDate,EndDate,RequestMade,FirstName,LastName,NAUEmail,ProjectName,ProjectObjective,ContactName,ContactID,Funding,SponsorName,SponsorPhone,SponsorEmail,Chemicals,MeetingTimes,GroupMembers,ProjectFile,Status,OwnerID")] Request request)
        {
            //var autoEmail = new MimeMessage();
            //autoEmail.From.Add(new MailboxAddress("donotreplyelims@gmail.com"));
            //autoEmail.To.Add(new MailboxAddress("bsb232@nau.edu"));
            ////Lab instructor emails
            //// autoEmail.To.Add(new MailboxAddress("terry.baxter@nau.edu"));
            //// autoEmail.To.Add(new MailboxAddress("adam.bringhurst@nau.edu"));
            //autoEmail.Subject = "ELIMS Contact Notification";
            //autoEmail.Body = new TextPart("plain")
            //{
            //    Text = @"A new request for lab usage has been submitted. Please click this link to manage: https://elims.azurewebsites.net/request. Do not reply to this email. Thank you!"
            //};

            //using (var client = new SmtpClient())
            //{
            //    client.ServerCertificateValidationCallback = (s, c, h, e) => true;


            //    client.Connect("smtp.gmail.com", 587, false);
            //    client.Authenticate("donotreplyelims@gmail.com", "NAULabs123");
            //    client.Send(autoEmail);
            //    client.Disconnect(true);
            //}

            if (ModelState.IsValid)
            {
                request.OwnerID = _userManager.GetUserId(User);

                var isAuthorized = await _authorizationService.AuthorizeAsync(User, request, ELIMSOperations.Create);

                // If not authorized
                if (!isAuthorized.Succeeded)
                {
                    return new ChallengeResult();
                }
                _context.Add(request);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(request);
        }

        // GET: Requests/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var request = await _context.Request.FindAsync(id);

            if (request == null)
            {
                return NotFound();
            }
            var isAuthorized = User.IsInRole("MANAGERS") || User.IsInRole("ADMINISTRATORS");

            var currentUserId = _userManager.GetUserId(User);

            if (!isAuthorized
                && currentUserId != request.OwnerID
                && request.Status != RequestStatus.Approved)
            {
                return new ChallengeResult();
            }

            return View(request);
        }

        // POST: Requests/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,StartDate,EndDate,RequestMade,FirstName,LastName,NAUEmail,ProjectName,ProjectObjective,ContactName,ContactID,Funding,SponsorName,SponsorPhone,SponsorEmail,Chemicals,MeetingTimes,GroupMembers,ProjectFile,Status,OwnerID")] Request request)
        {
            if (id != request.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //request.OwnerID = request.OwnerID;
                    _context.Update(request);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RequestExists(request.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(request);
        }


ELIMS_MVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@using ELIMS_MVC.Data;

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ELIMS</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><img src="~/images/home.png" alt="Little cartoon image of a house" style="width:30px;height:30px;"></a>
            </div>
            <div class="navbar-collapse collapse">
                <!--Where the navbar-nav ul went-->
                <ul class="nav navbar-nav" style="font-size:medium;">
                    @if (SignInManager.IsSignedIn(User) && (User.IsInRole("ADMINISTRATORS")))
                    {
                        @*<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>*@
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="ContactForms" asp-action="Index">Contact</a></li>
                        <li><a asp-area="" asp-controller="Request" asp-action="Index">Lab Requests</a></li>
                        <li><a asp-area="" asp-controller="LabSafety" asp-action="Index">Lab Safety</a></li>
                        <li><a asp-area="" asp-controller="Inventories" asp-action="Index">Inventory</a></li>
                        <li><a asp-area="" asp-controller="Dashboard" asp-action="Index">User Control</a></li>
                    }
                    else if (SignInManager.IsSignedIn(User) && User.IsInRole("MANAGERS"))
                    {
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="ContactForms" asp-action="Index">Contact</a></li>
                        <li><a asp-area="" asp-controller="Request" asp-action="Index">Lab Requests</a></li>
                        <li><a asp-area="" asp-controller="LabSafety" asp-action="Index">Lab Safety</a></li>
                        <li><a asp-area="" asp-controller="Inventories" asp-action="Index">Inventory</a></li>
                    }
                    else if (SignInManager.IsSignedIn(User) && User.IsInRole("USERS"))
                    {
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="ContactForms" asp-action="Index">Contact</a></li>
                        <li><a asp-area="" asp-controller="Request" asp-action="Index">Lab Requests</a></li>
                        <li><a asp-area="" asp-controller="LabSafety" asp-action="Index">Lab Safety</a></li>
                    }
                    else
                    {
                        @*<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>*@
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="ContactForms" asp-action="Create">Contact</a></li>
                    }
                </ul>

                <partial name="_LoginPartial" />

            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)



</body>

</html>